// Generated by https://quicktype.io

export interface Order {
    customerId:   string;
    date:         string;
    dueDate:      string;
    vatTotal:     number;
    subTotal:     number;
    total:        number;
    discount:     number;
    serie: string;
    comments: string,
    salesPersonCode: string
    orderDetails: OrderDetail[];
}

export interface OrderDetail {
    description:   string;
    aditionalInfo: string;
    discount:      number;
    amount:        number;
    value:         number;
    vat:           number;
    project:       string;
    wareHouseCode: number
}
