// Generated by https://quicktype.io

import { Customer } from "app/modules/contact/customer/clients.types";

export interface Order {
    customerId:   string;
    date:         string;
    dueDate:      string;
    vatTotal:     number;
    subTotal:     number;
    total:        number;
    discount:     number;
    estimatedDate: string;
    customer?: Customer;
    serie: string;
    comments: string,
    salesPersonCode: string
    orderDetails: OrderDetail[];
}

export interface OrderDetail {
    description:   string;
    aditionalInfo: string;
    discount:      number;
    amount:        number;
    value:         number;
    vat:           number;
    project:       string;
    wareHouseCode: number
}
