// Generated by https://quicktype.io



export interface report {
    identification:   string;
    details: OrderDetail[];
}

export interface OrderDetail {
    description:   string;
    aditionalInfo: string;
    discount:      number;
    amount:        number;
    value:         number;
    vat:           number;
    project:       string;
    wareHouseCode: number
}
