// Generated by https://quicktype.io

export interface Uhbt {
    id:        string;
    code:      string;
    name:      string;
    settingId: string;
    value?: string;
    createdAt: string;
    updatedAt: string;
}
