// Generated by https://quicktype.io

export interface User {
    userName:  string;
    password:  string;
    firstName: string;
    lastName:  string;
    email:     string;
    phone:     string;
    role:      string;
    active:    boolean;
}


export interface Photo {
    Location: string;
    Key:      string;
}


export const ROLE = [
    'Super Administrador',
    'Lider Comercial',
    'Vendedor/Comercial',
    'Caja',
    'Coordinador Logistica',
    'Conductor'
];


